### ISSUE TITLE
rnazCluster.pl. and rnazIndex.pl: gff with "+" and "-" DNA strand of ncRNA predictions

### ISSUE THREAD

**Issue by germant13** [ViennaRNA/RNAz#10]
Hi!
I am writing because I have a question about the rnazCluster.pl and rnazIndex.pl. I am trying to develop a pipeline to predict sRNA from bacterial genomes and rna-seq data (I use Salmonella genomes). I would like to incorporate into the pipeline the rnaz software. I run the program according to the manual. I executed the script rnazCluster.pl and rnazIndex.pl. But when I analyzed the results.dat and results.gff, the results.gff the strand column did not indicate "+"  or  "-" , the strand column indicate only a "." In the results.dat, in the loci lines did not indicate the strand, too. is it normal? What solution do you recommend me?
Would I like to know in the strand that the prediction is? Or I need to predict by other programs? What can you suggest me?

I attached the head of both file at the end of this e-mail

Regards

 
TRAGLIA GERMAN MATIAS, Ph.D
Computational Biology Lab
Department of Biotechnology Development
School of Medicine
University of the republic

results.dat
head results.dat 

locus1	LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	616248	4487105	6	99.25	0.994903	-2.85

window1	locus1	LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	4487036	4487105	+	6	69	98.07	-32.92	-32.45	-32.62	0.17	1.00	-2.85	0.92.74	0.994903	0.63653

window2	locus1	LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	616248	616408	+	6	160	97.70	-44.77	-44.49	-44.52	0.03	1.02	-2.03	0.91.86	0.972493	0.39691

window3	locus1	LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	616268	616428	-	6	160	99.25	-44.32	-44.03	-43.67	-0.36	1.04	-1.95	0.91.65	0.959313	0.38958

window4	locus1	LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	616288	616448	+	6	160	99.25	-35.53	-35.17	-34.81	-0.36	1.05	-2.01	0.91.73	0.964860	0.35208

window5	locus1	LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	616288	616448	-	6	160	99.25	-41.02	-41.09	-40.73	-0.36	1.04	-2.37	1.02.26	0.987170	0.35208

window6	locus1	LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	616308	616468	-	6	160	99.04	-36.03	-35.47	-34.97	-0.50	1.07	-2.09	0.91.74	0.965897	0.31562

window7	locus1	LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	616328	616487	+	6	160	98.25	-34.73	-33.32	-33.15	-0.17	1.07	-2.31	0.91.89	0.974274	0.30998

locus2	LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	616706	616966	4	99.69	0.996046	-3.06

window8	locus2	LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	616706	616866	-	4	160	99.69	-57.00	-57.00	-57.00	0.00	1.00	-3.06	1.02.88	0.996046	0.47656

results.gff
head results.gff 	

LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	RNAz	structuredRNA	616707	616966	0.996046	.	id "locus2"	

LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	RNAz	structuredRNA	617647	618144	0.998828	.	id "locus3"	

LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	RNAz	structuredRNA	618405	618604	0.990075	.	id "locus4"	

LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	RNAz	structuredRNA	618645	618804	0.905815	.	id "locus5"	

2511STDY5462413.fasta.LN890520.Salmonella.enterica.subsp.enterica.serovar.Weltevreden.genome.assembly.C2346	RNAz	structuredRNA	841878	842073	0.993562	.	id "locus6"	

LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	RNAz	structuredRNA	2170788	2171204	0.996955	.	id "locus7"	

LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	RNAz	structuredRNA	2171485	2171864	0.995285	.	id "locus8"	

LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	RNAz	structuredRNA	2171925	2172304	0.998424	.	id "locus9"	

LT2.fasta.AE006468.Salmonella.enterica.subsp.enterica.serovar.Typhimurium.str.LT2	RNAz	structuredRNA	2172865	2173624	0.998590	.	id "locus10"

**Comment by svenderheld** [comment]
Dear germant13,

according to the manual (see copied paragraph below [1]) it can be hard to decide which strand is the correct one because loci are most often composed of windows in either direction --- as it is the case in your example as well. That is why you cant find a strand information (in the gtf) files for loci. To get an educated guess you could apply RNAstrand [2], which exists as standalone tool and is also integrated in RNAz (try --predict-strand option; it is important to score both strands by RNAz but you did this anyways). To the best of my knowledge RNAstrand was trained on mono-nucleotide shuffled data only. In contrast RNAz 2.0 was trained on di-nucleotide data. If I got it right you plan to correlate your RNAz results with sequencing data. Depending on the protocol, the latter will hopefully tell you the strand anyway and you now know that the predictions need to be taken with caution.

I hope that helps?

Best,
Sven

[2] https://almob.biomedcentral.com/articles/10.1186/1748-7188-2-6

[1] "If you have a strong RNA signal in one strand you can observe in many cases also
a signal in the reverse complement. Usually the signals (SCI, z-score, consensus
MFE) are stronger in the “correct” direction. In most cases this also goes along
with a better P value. However, this is not always so care must be taken when
interpreting a RNAz result on data for which the reading direction is not known." copied from the RNAz-manual
